security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: phoneNumber
    firewalls:
        api:
            pattern: ^/api
            stateless: true
            json_login:
                username_path: phone_number
                check_path: /api/users/login
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure
            jwt: ~
            refresh_jwt:
                check_path: /api/auth/refresh
            entry_point: jwt
        admin:
            pattern: ^/admin
            provider: app_user_provider
            form_login:
                login_path: admin_login
                check_path: admin_login
                default_target_path: sonata_admin_dashboard
            logout:
                path: admin_logout
                target: admin_login

    access_control:
        - {
            path: ^/api/v1/users/(register|login|logout|refresh),
            roles: PUBLIC_ACCESS,
          }
        - { 
            path: ^/api/v1/(houses|cities|countries), 
            methods: [GET],
            roles: PUBLIC_ACCESS 
          }
        - {
            path: ^/api/v1/telegram,
            roles: PUBLIC_ACCESS,
        }
        - {
            path: ^/api/v1/docs,
            roles: PUBLIC_ACCESS,
        }

        - { path: ^/api/v1/users/me, roles: ROLE_USER }
        - { 
            path: ^/api/v1/bookings,
            roles: ROLE_USER 
          }
        
        - { 
            path: ^/api/v1/,
            roles: ROLE_ADMIN 
          }
          
        - { path: ^/admin/login$, roles: PUBLIC_ACCESS }
        - { path: ^/admin/, roles: ROLE_ADMIN }

when@test:
    security:
        password_hashers:
            # By default, password hashers are resource intensive and take time. This is
            # important to generate secure password hashes. In tests however, secure hashes
            # are not important, waste resources and increase test times. The following
            # reduces the work factor to the lowest possible values.
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4 # Lowest possible value for bcrypt
                time_cost: 3 # Lowest possible value for argon
                memory_cost: 10 # Lowest possible value for argon
